/*
 * بصريات العادل — «دقة برتقالية» المتصلة بلوحة التحكم.
 * تستقبل الصفحة النصوص والوسائط والألوان من نموذج محتوى منشور، مع الحفاظ على مسار العدسة والتركيب التحريري.
 */
import { trpc } from "@/lib/trpc";
import { filterFrames, frameFilterOptions } from "@shared/frameFilters";
import { DEFAULT_SITE_CONTENT, siteContentSchema, type SiteContent } from "@shared/siteContent";
import { createWhatsAppLink } from "@shared/whatsapp";
import { ArrowLeft, ArrowUpLeft, Clock3, Eye, Glasses, Menu, MessageCircle, Phone, Pin, ScanLine, ShieldCheck, Sun, X } from "lucide-react";
import { useState, type CSSProperties } from "react";

const serviceIcons = [Eye, Glasses, Sun];
const trustIcons = [ScanLine, Glasses, ShieldCheck];

function Media({ kind, src, className, alt }: { kind: "image" | "video"; src: string; className?: string; alt: string }) {
  if (!src) return null;
  return kind === "video" ? <video src={src} className={className} autoPlay muted loop playsInline controls={false} /> : <img src={src} className={className} alt={alt} />;
}

function CollectionSection({ content, branding, textColor }: { content: SiteContent; branding: SiteContent["branding"]; textColor: (key: string) => string }) {
  const [frameType, setFrameType] = useState("الكل");
  const [frameColor, setFrameColor] = useState("الكل");
  const frameTypes = frameFilterOptions(content.collection.items, "frameType");
  const frameColors = frameFilterOptions(content.collection.items, "frameColor");
  const visibleFrames = filterFrames(content.collection.items, { type: frameType, color: frameColor });

  return <section className="collection" id="collection" aria-labelledby="collection-heading"><div className="section-wrap"><div className="collection-head"><div><span className="eyebrow" style={{ color: textColor("collectionEyebrow") }}>{content.collection.eyebrow}</span><h2 className="section-title" id="collection-heading" style={{ fontFamily: `"${branding.displayFont}", sans-serif`, color: textColor("collectionTitle") }}>{content.collection.title} <span className="focus-word" style={{ color: textColor("collectionAccent") }}>{content.collection.accent}</span></h2><p className="section-copy" style={{ color: textColor("collectionDescription") }}>{content.collection.description}</p></div><a className="outline-button" style={{ color: textColor("collectionAction") }} href={content.collection.action.href}>{content.collection.action.label} <ArrowLeft size={17} /></a></div><div className="frame-filters" aria-label="تصفية الفريمات"><div className="filter-group"><span>النوع</span><div>{["الكل", ...frameTypes].map((type) => <button type="button" key={type} className={frameType === type ? "active" : ""} aria-pressed={frameType === type} onClick={() => setFrameType(type)}>{type}</button>)}</div></div><div className="filter-group"><span>اللون</span><div>{["الكل", ...frameColors].map((color) => <button type="button" key={color} className={frameColor === color ? "active" : ""} aria-pressed={frameColor === color} onClick={() => setFrameColor(color)}>{color}</button>)}</div></div></div><div className="collection-grid">{visibleFrames.map((item, index) => { const orderLink = createWhatsAppLink(content.contact.whatsappNumber, item.whatsappMessage || `أرغب بالاستفسار عن ${item.title}.`, content.collection.action.href); const isWhatsApp = orderLink.startsWith("https://wa.me/"); return <article className={`collection-card ${item.style === "illustration" ? "no-image" : ""}`} key={`${item.category}-${index}`}>{item.style === "media" ? <Media kind={item.mediaKind} src={item.mediaUrl} className="h-full w-full object-cover" alt={item.title} /> : <span className="collection-seal"><img src={branding.eyeMarkUrl} alt="" /></span>}<div className="collection-label"><span>{item.category} · {item.frameColor}</span><h3>{item.title}</h3><a className="frame-order" href={orderLink} target={isWhatsApp ? "_blank" : undefined} rel={isWhatsApp ? "noreferrer" : undefined}><MessageCircle size={15} /> اطلب عبر واتساب</a></div></article>; })}</div>{visibleFrames.length === 0 ? <p className="no-frames">لا توجد فريمات تطابق هذا الاختيار حاليًا. جرّب لونًا أو نوعًا آخر.</p> : null}</div></section>;
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const { data } = trpc.site.get.useQuery();
  const content = data ? siteContentSchema.parse(data) : DEFAULT_SITE_CONTENT;
  const { branding, hero } = content;
  const textColor = (key: string) => content.textColors[key] ?? branding.inkColor;
  const themeStyle = {
    "--orange": branding.primaryColor,
    "--orange-deep": branding.primaryColor,
    "--ink": branding.inkColor,
    "--cream": branding.creamColor,
    "--paper": "#fffdf8",
    fontFamily: `"${branding.bodyFont}", sans-serif`,
  } as CSSProperties;
  const closeMenu = () => setMenuOpen(false);

  return <div className="site-shell" dir="rtl" style={themeStyle}>
    <div className="top-ribbon"><div className="section-wrap ribbon-inner"><div className="ribbon-mark" style={{ color: textColor("ribbonText") }}><span /> {content.ribbon.notice}</div><a href={content.ribbon.link.href} style={{ color: textColor("ribbonLink") }}>{content.ribbon.link.label} <ArrowLeft size={13} strokeWidth={2.3} /></a></div></div>
    <header className="site-header"><div className="section-wrap header-inner"><a className="brand" href="#home" aria-label={`${branding.name} - الرئيسية`}><span className="brand-symbol"><img src={branding.eyeMarkUrl} alt="" /></span><span className="brand-wordmark"><img src={branding.logoUrl} alt={`شعار ${branding.name}`} /></span></a><nav className="desktop-nav" aria-label="التنقل الرئيسي">{content.navigation.map((item) => <a href={item.href} key={item.href}>{item.label}</a>)}</nav><div className="header-actions"><a className="header-call" href="#contact">تواصل مع الفرع</a><a className="cta-button" href="#products">تصفّح المنتجات <Glasses size={16} /></a><button className="mobile-menu" onClick={() => setMenuOpen((open) => !open)} aria-label={menuOpen ? "إغلاق القائمة" : "فتح القائمة"} aria-expanded={menuOpen}>{menuOpen ? <X size={20} /> : <Menu size={21} />}</button></div></div><nav className={`section-wrap mobile-nav ${menuOpen ? "open" : ""}`} aria-label="التنقل على الجوال">{content.navigation.map((item) => <a href={item.href} key={item.href} onClick={closeMenu}>{item.label}</a>)}</nav></header>
    <main>
      <section className="hero" id="home" aria-labelledby="hero-heading"><div className="hero-visual" aria-hidden="true"><Media kind={hero.mediaKind} src={hero.mediaUrl} className="h-full w-full object-cover" alt="" /></div><div className="hero-orbit" aria-hidden="true" /><p className="hero-vertical">AL ADEL · EYEWEAR</p><div className="section-wrap hero-grid"><div className="hero-content"><div className="hero-kicker" style={{ color: textColor("heroKicker") }}><span className="orbit-dot" /> {hero.kicker}</div><div className="hero-brand-seal" style={{ color: textColor("heroSeal") }}><img src={branding.eyeMarkUrl} alt="" /><span>{hero.sealText} <small>{hero.sealSubtext}</small></span></div><h1 id="hero-heading" style={{ fontFamily: `"${branding.displayFont}", sans-serif` }}><span style={{ color: textColor("heroTitleStart") }}>{hero.titleStart}</span> <em style={{ color: textColor("heroTitleAccent") }}>{hero.titleAccent}</em><br /><span style={{ color: textColor("heroTitleEnd") }}>{hero.titleEnd}</span></h1><p className="hero-copy" style={{ color: textColor("heroDescription") }}>{hero.description}</p><div className="hero-actions"><a className="cta-button" style={{ color: textColor("heroPrimaryAction") }} href={hero.primaryAction.href}>{hero.primaryAction.label} <ArrowLeft size={17} /></a><a className="outline-button" style={{ color: textColor("heroSecondaryAction") }} href={hero.secondaryAction.href}>{hero.secondaryAction.label} <ArrowUpLeft size={17} /></a></div><div className="hero-quickfacts" aria-label="مزايا بصريات العادل">{hero.quickFacts.map((fact) => <div className="quickfact" key={fact.number}><strong>{fact.number}</strong><span>{fact.label}</span></div>)}</div></div></div></section>
      <section className="trust-strip" aria-label="مزايا مختصرة"><div className="section-wrap trust-inner">{content.trustItems.map((item, index) => { const Icon = trustIcons[index % trustIcons.length]; return <div className="trust-item" key={item}><Icon size={20} /> {item}</div>; })}</div></section>
      <section className="services" id="services" aria-labelledby="services-heading"><div className="section-wrap"><div className="service-head"><div><span className="eyebrow" style={{ color: textColor("servicesEyebrow") }}>{content.services.eyebrow}</span><h2 className="section-title" id="services-heading" style={{ fontFamily: `"${branding.displayFont}", sans-serif`, color: textColor("servicesTitle") }}>{content.services.title} <span className="focus-word" style={{ color: textColor("servicesAccent") }}>{content.services.accent}</span></h2></div><p className="section-copy" style={{ color: textColor("servicesDescription") }}>{content.services.description}</p></div><div className="calibration-rail" aria-hidden="true"><span>مسار الوضوح</span><i /><span>عدسة</span><i /><span>فريم</span><i /><span>إطلالة</span></div><div className="service-grid">{content.services.items.map((item, index) => { const Icon = serviceIcons[index % serviceIcons.length]; return <article className="service-card" key={item.number}><span className="service-number">{item.number}</span><div className="service-icon"><Icon size={25} strokeWidth={1.7} /></div><h3>{item.title}</h3><p>{item.body}</p><ArrowLeft className="service-arrow" size={19} /></article>; })}</div></div></section>
      <CollectionSection content={content} branding={branding} textColor={textColor} />
      <section className="consultation" id="products" aria-labelledby="products-heading"><div className="section-wrap consultation-grid"><div className="consultation-image"><Media kind={content.products.mediaKind} src={content.products.imageUrl} className="h-full w-full object-cover" alt="عدسات وفريمات بصريات العادل" /><span className="image-tag">{content.products.imageTag}</span></div><div className="consultation-content"><span className="eyebrow" style={{ color: textColor("productsEyebrow") }}>{content.products.eyebrow}</span><h2 className="section-title" id="products-heading" style={{ fontFamily: `"${branding.displayFont}", sans-serif`, color: textColor("productsTitle") }}>{content.products.title} <span className="focus-word" style={{ color: textColor("productsAccent") }}>{content.products.accent}</span></h2><div className="steps" style={{ color: textColor("productsBody") }}>{content.products.items.map((item, index) => <div className="step" key={item}><strong>{index + 1}</strong><span>{item}</span></div>)}</div><div className="consultation-seal" style={{ color: textColor("productsBody") }}><img src={branding.eyeMarkUrl} alt="" /> {content.products.seal}</div><a className="cta-button" href={content.products.action.href} style={{ marginTop: "31px", alignSelf: "flex-start", color: textColor("productsAction") }}>{content.products.action.label} <Glasses size={16} /></a></div></div></section>
      <section className="offer" aria-labelledby="offer-heading"><div className="section-wrap offer-grid"><div className="offer-graphic" aria-hidden="true"><div className="offer-circle" /><div className="offer-frame" /></div><div className="offer-content"><span className="offer-label" style={{ color: textColor("offerLabel") }}>{content.offer.label}</span><h2 id="offer-heading" style={{ fontFamily: `"${branding.displayFont}", sans-serif`, color: textColor("offerTitle") }}>{content.offer.title} <span className="focus-word" style={{ color: textColor("offerAccent") }}>{content.offer.accent}</span></h2><p style={{ color: textColor("offerDescription") }}>{content.offer.description}</p>{(() => { const orderLink = createWhatsAppLink(content.contact.whatsappNumber, `أرغب بالاستفسار عن العرض: ${content.offer.title} ${content.offer.accent}`, content.offer.action.href); const isWhatsApp = orderLink.startsWith("https://wa.me/"); return <a className="cta-button" style={{ color: textColor("offerAction") }} href={orderLink} target={isWhatsApp ? "_blank" : undefined} rel={isWhatsApp ? "noreferrer" : undefined}>{content.offer.action.label} <MessageCircle size={16} /></a>; })()}</div></div></section>
      {content.customSections.filter((section) => section.visible).map((section) => <section className="custom-section" key={section.id}><div className="section-wrap custom-section-grid"><div className="custom-section-copy"><span className="eyebrow">{section.eyebrow}</span><h2 className="section-title" style={{ fontFamily: `"${branding.displayFont}", sans-serif` }}>{section.title}</h2><p className="section-copy">{section.description}</p><a className="cta-button" style={{ color: textColor("customAction") }} href={section.action.href}>{section.action.label} <ArrowLeft size={16} /></a></div>{section.mediaUrl ? <div className="custom-section-media"><Media kind={section.mediaKind} src={section.mediaUrl} className="h-full w-full object-cover" alt={section.title} /></div> : null}</div></section>)}
      <section className="contact" id="contact" aria-labelledby="contact-heading"><div className="section-wrap"><div className="contact-top"><div><span className="eyebrow" style={{ color: textColor("contactEyebrow") }}>{content.contact.eyebrow}</span><h2 className="section-title" id="contact-heading" style={{ fontFamily: `"${branding.displayFont}", sans-serif`, color: textColor("contactTitle") }}>{content.contact.title} <span className="focus-word" style={{ color: textColor("contactAccent") }}>{content.contact.accent}</span></h2></div><div className="contact-side"><p style={{ color: textColor("contactDescription") }}>{content.contact.description}</p><a className="outline-button" style={{ color: textColor("contactReturn") }} href="#home">العودة إلى البداية <ArrowUpLeft size={17} /></a></div></div><div className="contact-cards"><div className="contact-card"><Phone size={21} strokeWidth={1.9} /><small>{content.contact.phoneLabel}</small><strong className="details-await">{content.contact.phone}</strong></div><div className="contact-card"><Clock3 size={21} strokeWidth={1.9} /><small>{content.contact.hoursLabel}</small><strong className="details-await">{content.contact.hours}</strong></div><div className="contact-card"><Pin size={21} strokeWidth={1.9} /><small>{content.contact.locationLabel}</small><strong className="details-await">{content.contact.location}</strong></div></div><a href={content.contact.mapUrl || undefined} target={content.contact.mapUrl ? "_blank" : undefined} rel="noreferrer" className="map-placeholder"><div className="map-content"><span><Pin size={22} /></span><strong>{content.contact.mapTitle}</strong><p>{content.contact.mapDescription}</p></div></a></div></section>
    </main>
    <footer className="footer" style={{ color: textColor("footerText") }}><div className="section-wrap"><div className="footer-top"><div className="footer-brand"><img src={branding.eyeMarkUrl} alt={`رمز ${branding.name}`} /><p>{content.footer.description}</p></div><nav className="footer-links" aria-label="روابط التذييل">{content.navigation.slice(1).map((item) => <a href={item.href} key={item.href}>{item.label}</a>)}</nav></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {branding.name}. {content.footer.copyright}</span><span>{content.footer.note}</span></div></div></footer>
  </div>;
}
